const { escapeHtml: e } = require('./layout');
const interests = { automation: 'AI automation', 'custom-pcs': 'Custom gaming PC', 'local-ai': 'Business local AI system', websites: 'Website or custom app' };
function field(id, label, options) {
  return `<label class="plan-field" for="${id}"><span>${label}</span><select id="${id}" name="${id}">${options.map(([v,t]) => `<option value="${v}">${t}</option>`).join('')}</select></label>`;
}
function number(id,label,value,max,step='1') { return `<label class="plan-field" for="${id}"><span>${label}</span><input id="${id}" name="${id}" type="number" min="0" max="${max}" step="${step}" value="${value}" required></label>`; }
function wrap(id,title,intro,body) { return `<section class="section plan-section" id="${id}"><div class="container"><div class="section-head"><p class="eyebrow">Work out your next step</p><h2 class="section-title">${title}</h2><p class="section-sub">${intro}</p></div>${body.replace(/<button /g,'<button disabled ')}<noscript><p>Enable JavaScript to change this example. You can still read the guide and use the consultation link to discuss your project.</p></noscript></div></section>`; }
function handoff(type,label) { return `<a class="btn btn-primary" data-plan-handoff="${type}" href="/?interest=${encodeURIComponent(interests[type])}#audit">${label} →</a>`; }
function calculator() {
  return wrap('value-calculator','Is this task worth automating?','Try your own numbers. See the result without sharing your email.', `<form class="plan-tool" data-planner="automation"><div class="plan-fields">${number('task-count','Tasks per month',200,100000)}${number('task-minutes','Minutes per task',8,1440,'0.1')}${number('hourly-value','Value of an hour ($)',40,10000,'0.01')}${number('automation-share','Work removed (%)',60,100)}${number('review-hours','Review hours per month',5,10000,'0.1')}${number('setup-cost','One-time setup ($)',1250,1000000,'0.01')}${number('monthly-cost','Monthly tools and support ($)',50,100000,'0.01')}</div><div class="plan-output"><p class="eyebrow">Your scenario</p><h3 data-plan-title>11 hours of capacity per month</h3><p data-plan-result>$390 per month after the example ongoing cost. Setup recovery: about 3.2 months.</p><p class="plan-note">Capacity value is not a guaranteed cash saving. Include all software and support fees; monthly Ahern AI support is optional and is not included in the $50 example.</p><details><summary>How the estimate works</summary><p>Net hours = tasks × minutes ÷ 60 × work removed − review hours. Monthly value = net hours × hourly value − ongoing costs. Setup recovery = setup cost ÷ positive monthly value. These are your assumptions, not a quote.</p></details><button class="btn btn-ghost" type="submit">Update my estimate</button>${handoff('automation','Discuss this workflow')}<p class="plan-status" role="status" aria-live="polite"></p></div></form><noscript><p>Use the formula above, or <a href="/?interest=AI%20automation#audit">discuss your workflow</a>. JavaScript enables the calculator.</p></noscript>`);
}
function privateAI() {
  return wrap('ai-fit','Start with the job. Then choose the hardware.','A short fit check gives you a starting recommendation. No documents or contact details required.', `<form class="plan-tool" data-planner="local-ai"><div class="plan-fields">${field('ai-task','What should AI help with?', [['documents','Find answers in documents'],['drafting','Draft and summarize'],['coding','Assist with code'],['unsure','Help me decide']])}${field('ai-documents','What are your source files?', [['text','Searchable documents'],['scans','Scans or mixed file types'],['none','No collection ready yet']])}${field('ai-users','How many simultaneous users?', [['one','One person'],['small','2–5 people'],['team','6 or more people']])}${field('ai-boundary','Can the work use cloud services?', [['local','Keep processing on my hardware'],['hybrid','Some cloud use is acceptable'],['unsure','I need help deciding']])}${field('ai-hardware','What hardware is available?', [['existing','A computer I would like to reuse'],['new','I expect to buy hardware'],['unsure','Not sure yet']])}</div><div class="plan-output"><p class="eyebrow">Your starting point</p><h3 data-plan-title>A document assistant pilot</h3><p data-plan-result>Test one document collection and a set of real questions before choosing a system.</p><p class="plan-note">A fit check, not a hardware specification or a security certification. The pilot and deployment are individually quoted.</p><button class="btn btn-ghost" type="submit">Check my fit</button>${handoff('local-ai','Discuss my private AI plan')}<p class="plan-status" role="status" aria-live="polite"></p></div></form>`);
}
function documentDemo() {
  return wrap('document-demo','An answer you can check.','Explore a fictional workshop handbook. This is a preset browser demonstration, not a running AI model.', `<div class="document-example" data-document-demo><div><p class="eyebrow">Sample handbook · section 2</p><h3>Workshop delivery process</h3><p>Before pickup, the technician records the installed components and completes a stability check. A walkthrough covers basic operation and the agreed support contact. Delivery dates are confirmed individually.</p><p class="plan-note">Fictional training material. These sentences illustrate document search and are not customer results or service terms.</p></div><div><label class="plan-field" for="document-question"><span>Choose a question</span><select id="document-question"><option value="supported">What happens before pickup?</option><option value="unsupported">What is the warranty length?</option></select></label><button type="button" class="btn btn-ghost" data-document-run>Show sample answer</button><div class="document-answer" role="status" aria-live="polite"><strong data-answer-title>Before pickup</strong><p data-answer>The technician records components and completes a stability check.</p><p data-citation>Source: Workshop delivery process, section 2.</p></div><p class="plan-note">A deployed system needs access controls, source checks, and testing on your documents. This demo sends nothing to an AI service.</p></div></div>`);
}
function websitePlanner() {
  return wrap('website-fit','What happens after someone clicks Send?','Check the four handoffs that make a website useful to your business.', `<form class="plan-tool" data-planner="websites"><div class="plan-fields">${field('web-action','Is the visitor’s next action clear?', [['yes','Yes, one clear action'],['no','No / not sure']])}${field('web-destination','Do inquiries reach one managed inbox or CRM?', [['yes','Yes'],['no','No / not sure']])}${field('web-owner','Does someone own the response?', [['yes','Yes, with a response expectation'],['no','No / not sure']])}${field('web-tracking','Can you tell which inquiries became work?', [['yes','Yes'],['no','No / not sure']])}</div><div class="plan-output"><p class="eyebrow">Your intake check</p><h3 data-plan-title>Four handoffs to review</h3><p data-plan-result>Use your answers to identify the next improvement. This checks your process; it does not scan your website.</p><button class="btn btn-ghost" type="submit">Review my intake</button>${handoff('websites','Plan my connected website')}<p class="plan-status" role="status" aria-live="polite"></p></div></form>`);
}
function webDemo() {
  return wrap('intake-demo','From website inquiry to a clear next step.','Follow a fictional request through the intake process. No message is sent.', `<div class="intake-example" data-intake-demo><p><strong>Sample request:</strong> “We need a quieter editing workstation. Can we discuss a build?”</p><ol class="intake-steps"><li><strong>Capture</strong><p>Validate the contact details and preserve the requested service.</p></li><li><strong>Save once</strong><p>A request reference prevents a retry from creating the same inquiry twice.</p></li><li><strong>Notify</strong><p>Send the saved inquiry to the configured inbox; failed notifications remain queued.</p></li><li><strong>Human handoff</strong><p>Mike reviews the request, confirms fit, and arranges a conversation.</p></li></ol><button type="button" class="btn btn-ghost" data-intake-next>Follow the request</button><p data-intake-status role="status" aria-live="polite">Ready · 0 of 4 steps</p><p class="plan-note">Illustration of the intended process. Each client’s integrations and delivery checks are agreed before launch.</p></div>`);
}
function cards(title,items) { return `<section class="section section-alt"><div class="container"><h2 class="section-title">${title}</h2><div class="offer-grid">${items.map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></div></section>`; }
function offers(slug) {
  if(slug==='automation') return cards('Choose a job worth fixing.',[
    ['Lead Response Quickstart','One intake source, one destination, agreed routing, and an approved response method. From $1,250 when the scope fits. Acceptance checks cover missing details, duplicates, and failed handoffs.'],
    ['Inbox Triage Quickstart','One mailbox, agreed categories, and replies prepared for review. From $1,250 when the scope fits. Test a representative sample and route uncertainty to a person.'],
    ['Connected Follow-up Sprint','Two or three connected workflows, team training, and 30 days of tuning. $4,500 for an agreed scope. Historical cleanup, complex migrations, and custom apps are quoted separately.']]);
  if(slug==='custom-pcs') return cards('The build is only part of the experience.',[
    ['A recommendation with reasons','We balance the machine around your games or applications, budget, noise preference, and upgrade plans. Exact components and compatibility are confirmed in your quote.'],
    ['Testing and a clear handoff','Agree the test workload before the build. Your handoff records the installed components, setup notes, and completed checks. Any benchmark is tied to the tested configuration.'],
    ['Help moving in','Data migration, application setup, and an on-site walkthrough can be added to the quote. Devices, data volume, travel, and troubleshooting are scoped separately.'],
    ['Care when you need it','Discuss an annual cleaning and health check, an upgrade, or scoped business workstation support. Parts and unrelated repairs are separate; warranty and support terms are confirmed in writing.']]);
  if(slug==='local-ai') return cards('Prove the fit before the full deployment.',[
    ['1 · Scope a paid pilot','One document collection, one user group, and an agreed set of test questions. You receive a written recommendation to proceed, revise, or stop. Pilot price is confirmed before work begins.'],
    ['2 · Deploy the validated system','Hardware, model setup, document ingestion, access controls, and training are quoted together with clear line items. Reuse suitable hardware where possible.'],
    ['3 · Keep it useful','Optional Private AI Care covers the agreed systems: monitoring, document freshness, approved updates, and periodic answer-quality checks. Usage, support hours, and backup responsibilities are defined in your quote.']]);
  return cards('A clear scope, from launch to care.',[
    ['The Front Door','A website and a connected inquiry process, starting at $6,500. Your quote defines page count, content, one primary intake journey, integrations, testing, and training.'],
    ['Custom tools, scoped first','Dashboards, portals, and internal applications: $18,000–45,000. User roles, integrations, data migration, and reporting determine the scope. Substantial discovery is a separately quoted milestone.'],
    ['Care and improvement','The included first year of care has a defined maintenance allowance. New pages, new integrations, and conversion projects are separately scoped so you can choose what to invest in next.']]);
}
function ownership(slug) { return `<section class="section"><div class="container service-details"><div><p class="eyebrow">Clear ownership</p><h2 class="section-title">Know what you receive.</h2><p>Your quote identifies the hardware, accounts, source or workflow exports, documentation, and access included in the handoff. Third-party licenses and reusable Ahern AI components are explained separately.</p></div><div><p class="eyebrow">After delivery</p><p>We agree acceptance checks, support hours, and how to request changes before work starts. Ongoing help is optional and scoped. Existing client agreements keep their agreed terms.</p><a class="text-link" href="/resources#${slug}">Prepare for your ${slug==='custom-pcs'?'build':'project'} →</a></div></div></section>`; }
const guides = [
 ['automation','Before your first automation','Write down one repetitive task, how often it happens, minutes per task, the tools involved, and who handles exceptions. Include the cost of software and review time.','Bring three representative examples with personal information removed. Decide which steps need approval. Agree how to tell whether the workflow helped.'],
 ['custom-pcs','Before your next PC','List your main games or applications, display resolution, budget, noise preference, available desk space, and parts you want to reuse.','Include data migration, software licenses, monitors, delivery, tax, and setup in your total budget. A representative estimate becomes a final quote only after compatibility and availability checks.'],
 ['local-ai','Before a private AI pilot','Choose one job and a small representative document set. Identify scanned files, document owners, simultaneous users, and whether any cloud processing is permitted.','Prepare questions with known answers and questions the documents cannot answer. Agree quality, response time, source references, access boundaries, and ongoing support. Do not send private documents through the public form.'],
 ['websites','Before a connected website','Identify the visitor, the action you want them to take, where inquiries should land, who responds, and how you track paid work.','Bring your current site, content ownership details, required pages, integrations, and launch target. Define hosting, backups, maintenance allowances, and future improvement work separately.']
];
function resourcesHtml() { return `<section class="container service-hero"><p class="eyebrow">Free planning guides</p><h1>A better brief.<br>A better starting point.</h1><p class="section-sub">Four practical checklists to help you choose the right work. Read them here or print a copy. No email required.</p><button class="btn btn-ghost" type="button" data-print-guides>Print these guides</button></section>${guides.map(([slug,h,p,q])=>`<section class="section resource-guide" id="${slug}"><div class="container narrow"><h2 class="section-title">${e(h)}</h2><p>${e(p)}</p><p>${e(q)}</p><a class="text-link" href="/services/${slug}">Explore ${e(slug==='custom-pcs'?'custom PCs':slug==='local-ai'?'private AI':slug)} →</a></div></section>`).join('')}`; }
function experience(slug) {return offers(slug)+(slug==='automation'?calculator():slug==='local-ai'?privateAI()+documentDemo():slug==='websites'?websitePlanner()+webDemo():'')+ownership(slug);}
module.exports={ experience, resourcesHtml };
